service:
    name: <SERVICE_NAME>
    mode: 'devl'
    development_port: <SERVICE_PORT>
    description: 'Some short description about the service.'
    apidoc_dir: 'docs/_build'
    readme: 'README.md'
    allowed_hosts:
        - '*'
    use_prometheus: true
    use_default_endpoints:
        - alive
        - config
external_resources:
    api:
        url: <EXTERNAL_SERVICE_URL>
logger:
    path: <PATH_TO_STORE_LOGFILES>
    filename: 'service_{mode}.log'
    level: 'debug'
    rotation: '1 days'
    retention: '1 months'
    format: '{time:YYYY-MM-DD at HH:mm:ss} | {level} | {message}'
available_environment_variables:
    env_vars:
        - SERVICE__MODE
        - SERVICE__DEVELOPMENT_PORT
        - LOGGER__LEVEL
        - LOGGER__PATH
        - LOGGER__FILENAME
        - LOGGER__ROTATION
        - LOGGER__RETENTION
        - LOGGER__FORMAT
    external_resources_env_vars:
        - EXTERNAL_RESOURCES__API__URL
    rules_env_vars: []
